_format_version: "3.0"
services:
  - connect_timeout: 60000
    enabled: true
    host: localhost
    name: swagger-petstore
    path: /
    port: 443
    protocol: https
    read_timeout: 60000
    retries: 5
    routes:
      - https_redirect_status_code: 426
        methods:
          - POST
        name: swagger-petstore_addpet
        path_handling: v0
        paths:
          - ~/pet$
        preserve_host: false
        protocols:
          - http
          - https
        regex_priority: 200
        request_buffering: true
        response_buffering: true
        strip_path: false
      - https_redirect_status_code: 426
        methods:
          - POST
        name: swagger-petstore_createuser
        path_handling: v0
        paths:
          - ~/user$
        preserve_host: false
        protocols:
          - http
          - https
        regex_priority: 200
        request_buffering: true
        response_buffering: true
        strip_path: false
      - https_redirect_status_code: 426
        methods:
          - POST
        name: swagger-petstore_createuserswitharrayinput
        path_handling: v0
        paths:
          - ~/user/createWithArray$
        preserve_host: false
        protocols:
          - http
          - https
        regex_priority: 200
        request_buffering: true
        response_buffering: true
        strip_path: false
      - https_redirect_status_code: 426
        methods:
          - POST
        name: swagger-petstore_createuserswithlistinput
        path_handling: v0
        paths:
          - ~/user/createWithList$
        preserve_host: false
        protocols:
          - http
          - https
        regex_priority: 200
        request_buffering: true
        response_buffering: true
        strip_path: false
      - https_redirect_status_code: 426
        methods:
          - DELETE
        name: swagger-petstore_deleteorder
        path_handling: v0
        paths:
          - ~/store/order/(?<orderid>[^#?/]+)$
        preserve_host: false
        protocols:
          - http
          - https
        regex_priority: 100
        request_buffering: true
        response_buffering: true
        strip_path: false
      - https_redirect_status_code: 426
        methods:
          - DELETE
        name: swagger-petstore_deletepet
        path_handling: v0
        paths:
          - ~/pet/(?<petid>[^#?/]+)$
        preserve_host: false
        protocols:
          - http
          - https
        regex_priority: 100
        request_buffering: true
        response_buffering: true
        strip_path: false
      - https_redirect_status_code: 426
        methods:
          - DELETE
        name: swagger-petstore_deleteuser
        path_handling: v0
        paths:
          - ~/user/(?<username>[^#?/]+)$
        preserve_host: false
        protocols:
          - http
          - https
        regex_priority: 100
        request_buffering: true
        response_buffering: true
        strip_path: false
      - https_redirect_status_code: 426
        methods:
          - GET
        name: swagger-petstore_findpetsbystatus
        path_handling: v0
        paths:
          - ~/pet/findByStatus$
        preserve_host: false
        protocols:
          - http
          - https
        regex_priority: 200
        request_buffering: true
        response_buffering: true
        strip_path: false
      - https_redirect_status_code: 426
        methods:
          - GET
        name: swagger-petstore_findpetsbytags
        path_handling: v0
        paths:
          - ~/pet/findByTags$
        preserve_host: false
        protocols:
          - http
          - https
        regex_priority: 200
        request_buffering: true
        response_buffering: true
        strip_path: false
      - https_redirect_status_code: 426
        methods:
          - GET
        name: swagger-petstore_getinventory
        path_handling: v0
        paths:
          - ~/store/inventory$
        preserve_host: false
        protocols:
          - http
          - https
        regex_priority: 200
        request_buffering: true
        response_buffering: true
        strip_path: false
      - https_redirect_status_code: 426
        methods:
          - GET
        name: swagger-petstore_getorderbyid
        path_handling: v0
        paths:
          - ~/store/order/(?<orderid>[^#?/]+)$
        preserve_host: false
        protocols:
          - http
          - https
        regex_priority: 100
        request_buffering: true
        response_buffering: true
        strip_path: false
      - https_redirect_status_code: 426
        methods:
          - GET
        name: swagger-petstore_getpetbyid
        path_handling: v0
        paths:
          - ~/pet/(?<petid>[^#?/]+)$
        preserve_host: false
        protocols:
          - http
          - https
        regex_priority: 100
        request_buffering: true
        response_buffering: true
        strip_path: false
      - https_redirect_status_code: 426
        methods:
          - GET
        name: swagger-petstore_getuserbyname
        path_handling: v0
        paths:
          - ~/user/(?<username>[^#?/]+)$
        preserve_host: false
        protocols:
          - http
          - https
        regex_priority: 100
        request_buffering: true
        response_buffering: true
        strip_path: false
        tags:
          - teste
      - https_redirect_status_code: 426
        methods:
          - GET
        name: swagger-petstore_loginuser
        path_handling: v0
        paths:
          - ~/user/login$
        preserve_host: false
        protocols:
          - http
          - https
        regex_priority: 200
        request_buffering: true
        response_buffering: true
        strip_path: false
      - https_redirect_status_code: 426
        methods:
          - GET
        name: swagger-petstore_logoutuser
        path_handling: v0
        paths:
          - ~/user/logout$
        preserve_host: false
        protocols:
          - http
          - https
        regex_priority: 200
        request_buffering: true
        response_buffering: true
        strip_path: false
      - https_redirect_status_code: 426
        methods:
          - POST
        name: swagger-petstore_placeorder
        path_handling: v0
        paths:
          - ~/store/order$
        preserve_host: false
        protocols:
          - http
          - https
        regex_priority: 200
        request_buffering: true
        response_buffering: true
        strip_path: false
      - https_redirect_status_code: 426
        methods:
          - PUT
        name: swagger-petstore_updatepet
        path_handling: v0
        paths:
          - ~/pet$
        preserve_host: false
        protocols:
          - http
          - https
        regex_priority: 200
        request_buffering: true
        response_buffering: true
        strip_path: false
      - https_redirect_status_code: 426
        methods:
          - POST
        name: swagger-petstore_updatepetwithform
        path_handling: v0
        paths:
          - ~/pet/(?<petid>[^#?/]+)$
        preserve_host: false
        protocols:
          - http
          - https
        regex_priority: 100
        request_buffering: true
        response_buffering: true
        strip_path: false
      - https_redirect_status_code: 426
        methods:
          - PUT
        name: swagger-petstore_updateuser
        path_handling: v0
        paths:
          - ~/user/(?<username>[^#?/]+)$
        preserve_host: false
        protocols:
          - http
          - https
        regex_priority: 100
        request_buffering: true
        response_buffering: true
        strip_path: false
      - https_redirect_status_code: 426
        methods:
          - POST
        name: swagger-petstore_uploadfiles
        path_handling: v0
        paths:
          - ~/pet/(?<petid>[^#?/]+)/uploadImages$
        preserve_host: false
        protocols:
          - http
          - https
        regex_priority: 100
        request_buffering: true
        response_buffering: true
        strip_path: false
    write_timeout: 60000
