_format_version: "3.0"
services:
  - connect_timeout: 60000
    enabled: true
    host: httpbin.org
    name: sample-httpbin-v1
    path: /
    port: 443
    protocol: https
    read_timeout: 60000
    retries: 5
    tags:
      - sample
    write_timeout: 60000
  - connect_timeout: 60000
    enabled: true
    host: petstore.swagger.io
    name: sample-petstore-v1
    path: /v2
    port: 443
    protocol: https
    read_timeout: 60000
    retries: 5
    routes:
      - https_redirect_status_code: 426
        name: sample-acl-v1
        path_handling: v0
        paths:
          - /sample/v1/acl
        plugins:
          - config:
              allow:
                - group1
                - group2
              deny: null
              hide_groups_header: true
            enabled: true
            instance_name: sample-acl-v1
            name: acl
            protocols:
              - grpc
              - grpcs
              - http
              - https
            tags:
              - sample
              - acl
        preserve_host: false
        protocols:
          - http
          - https
        regex_priority: 0
        request_buffering: true
        response_buffering: true
        strip_path: true
        tags:
          - sample
          - acl
    tags:
      - sample
    write_timeout: 60000
