ingressController:
  enabled: false
  env:
    publish_service: kong/kong-dp-kong-proxy
    kong_admin_token: kong_admin_password

image:
  repository: kong
  tag: "3.8.0"

secretVolumes:
  - kong-cluster-cert

env:
  role: control_plane
  # Esses certificados são usados para comunicação entre control plane / data plane
  cluster_cert: /etc/secrets/kong-cluster-cert/tls.crt
  cluster_cert_key: /etc/secrets/kong-cluster-cert/tls.key

  admin_gui_url: https://manager.kong.local # Manager
  admin_gui_api_url: https://admin.kong.local # Admin
  admin_gui_session_conf: '{"secret":"secret","storage":"kong","cookie_secure":false}'

  KONG_LOG_LEVEL: debug
  KONG_PLUGINS: "bundled, my-plugin"
  KONG_LUA_PACKAGE_PATH: "/usr/local/share/lua/5.1/?.lua;;"

  database: postgres
  pg_database: kong
  pg_user: kong
  pg_password: demo123
  pg_host: kong-cp-postgresql.kong.svc.cluster.local
  pg_ssl: "on"

  password: kong_admin_password

plugins:
  configMaps:
    - pluginName: my-plugin # kong plugin display name
      name: kong-plugin-my-plugin # configmap

enterprise:
  enabled: false

admin:
  enabled: true
  http:
    enabled: true
  tls:
    enabled: false
  ingress:
    enabled: true
    hostname: admin.kong.local
    path: /
    pathType: Prefix
    ingressClassName: nginx

cluster:
  enabled: true
  tls:
    enabled: true

clustertelemetry:
  enabled: true
  tls:
    enabled: true

manager:
  enabled: true
  http:
    enabled: true
  tls:
    enabled: false

  ingress:
    enabled: true
    hostname: manager.kong.local
    path: /
    pathType: Prefix
    ingressClassName: nginx

proxy:
  enabled: false

postgresql:
  enabled: true
  auth:
    password: demo123
