ingressController:
  enabled: false

image:
  repository: kong
  tag: "3.8.0"

# plugins:
#   enabled:
#     - traceheader-lua

# Mount the secret created earlier
secretVolumes:
  - kong-cluster-cert

gateway:
  plugins:
    # configMaps:
    # - pluginName: rewriter
    #   name: kong-plugin-rewriter
    configMaps:
      - pluginName: traceheader-lua
        name: kong-plugin-traceheader-lua
      - pluginName: my-plugin
        name: kong-plugin-my-plugin

env:
  # data_plane nodes do not have a database
  role: data_plane
  database: "off"

  # Tell the data plane how to connect to the control plane
  cluster_control_plane: kong-cp-kong-cluster.kong.svc.cluster.local:8005
  cluster_telemetry_endpoint: kong-cp-kong-clustertelemetry.kong.svc.cluster.local:8006

  # Configure control plane / data plane authentication
  lua_ssl_trusted_certificate: /etc/secrets/kong-cluster-cert/tls.crt
  cluster_cert: /etc/secrets/kong-cluster-cert/tls.crt
  cluster_cert_key: /etc/secrets/kong-cluster-cert/tls.key

  KONG_LUA_PACKAGE_PATH: "/usr/local/share/lua/5.1/?.lua;;"

# Enterprise functionality
enterprise:
  enabled: false

# The data plane handles proxy traffic only
proxy:
  enabled: true

# These roles are served by the kong-cp deployment
admin:
  enabled: false

manager:
  enabled: false
