ingressController:
  enabled: true
  env:
    publish_service: kong/kong-dp-kong-proxy
    kong_admin_token: kong_admin_password

image:
  repository: kong
  tag: "3.8.0"

secretVolumes:
  - kong-cluster-cert

env:
  role: control_plane
  # Esses certificados são usados para comunicação entre control plane / data plane
  cluster_cert: /etc/secrets/kong-cluster-cert/tls.crt
  cluster_cert_key: /etc/secrets/kong-cluster-cert/tls.key

  admin_gui_url: http://localhost:8002/ # Manager
  admin_gui_api_url: http://localhost:8001 # Admin
  admin_gui_session_conf: '{"secret":"secret","storage":"kong","cookie_secure":false}'

  KONG_PLUGINS: "bundled,traceheader-lua, my-plugin" # Adicione seu plugin aqui
  KONG_LUA_PACKAGE_PATH: "/usr/local/share/lua/5.1/?.lua;;"

  database: postgres
  pg_database: kong
  pg_user: kong
  pg_password: demo123
  pg_host: kong-cp-postgresql.kong.svc.cluster.local
  pg_ssl: "on"

  password: kong_admin_password

  # gateway:
plugins:
  # configMaps:
  # - pluginName: rewriter
  #   name: kong-plugin-rewriter
  configMaps:
    - pluginName: traceheader-lua
      name: kong-plugin-traceheader-lua
    - pluginName: my-plugin
      name: kong-plugin-my-plugin

enterprise:
  enabled: false

admin:
  enabled: true
  http:
    enabled: true
  tls:
    enabled: false
  ingress:
    enabled: true
    hostname: admin.kong.local
    path: /
    pathType: Prefix
    ingressClassName: kong

cluster:
  enabled: true
  tls:
    enabled: true

clustertelemetry:
  enabled: true
  tls:
    enabled: true

manager:
  enabled: true
  http:
    enabled: true
  tls:
    enabled: false

  ingress:
    enabled: true
    hostname: manager.kong.local
    path: /
    pathType: Prefix
    ingressClassName: kong

proxy:
  enabled: false

postgresql:
  enabled: true
  auth:
    password: demo123
